baseURL = "https://nichecode.github.io/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Nicholas Hammond"
theme = "congo"

enableRobotsTXT = true

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]