# Theme parameters
colorScheme = "default"
defaultAppearance = "dark"
autoSwitchAppearance = false

# Enable site search
enableSearch = true
enableCodeCopy = true

# SEO
robots = "index, follow"

# Site header configuration
[header]
  layout = "hybrid"
  showTitle = true

# Site footer configuration
[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = false
  showScrollToTop = true

# Article configuration
[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = true
  sharingLinks = ["github"]

# Home page configuration
[homepage]
  layout = "profile"
  showRecent = true
  recentLimit = 5

[list]
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = false
  showTaxonomies = true
  groupByYear = true
  paginationWidth = 1